//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.TournamentScores = new HashSet<TournamentScore>();
        }
    
        public int TournamentID { get; set; }
        [DisplayName("Opponent Name")]
        public string TournamentName { get; set; }
        [DisplayName("League")]
        public Nullable<int> LeagueID { get; set; }
        [DisplayName("Opponent Rank")]
        public Nullable<int> Rank { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TournamentScore> TournamentScores { get; set; }
        public virtual League League { get; set; }
    }
}
